name: awesome-chatgpt-prompts-updates

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0
        
      - name: Check if files are the same
        id: check-files
        run: |
          curl -sS "https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv" -o "prompts-new.csv"
          if ! cmp -s "prompts.csv" "prompts-new.csv"; then
            cp "prompts-new.csv" "prompts.csv"
            echo "Updated!"
            echo "updated=true" >> $GITHUB_OUTPUT
            pip install csvkit
            sed -i '1s/act/key/g' prompts.csv
            sed -i '1s/prompt/value/g' prompts.csv
            csvjson prompts.csv > prompts.json
            echo "JSON conversion successful"
          else
            echo "They are the same. No action needed."
            echo "updated=false" >> $GITHUB_OUTPUT
            pip install csvkit
            sed -i '1s/act/key/g' prompts.csv
            sed -i '1s/prompt/value/g' prompts.csv
            csvjson prompts.csv > prompts.json
            echo "JSON conversion successful"
          fi

      - name: Update file in main branch
        # if: steps.check_file.outputs.updated == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated!" -a
          git push
          

