name: awesome-chatgpt-prompts-updates

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0
        
      - name: Check if files are the same
        id: check-file
        run: |
          curl -sS "https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv" -o "prompts-new.csv"
          
          set -euo pipefail
          
          if cmp -s prompts-new.csv prompts.csv; then
              echo "prompts-new.csv and prompts.csv contain the same data. No update needed."
              echo "updated=false" >> $GITHUB_OUTPUT
          else
              echo "The contents of prompts-new.csv and prompts.csv are different."
              diff -u prompts-new.csv prompts.csv || true
              cp prompts-new.csv prompts.csv
              echo "prompts.csv has been updated with the contents of prompts-new.csv."
              echo "updated=true" >> $GITHUB_OUTPUT
              
              if ! command -v csvjson >/dev/null 2>&1; then
                  echo "csvkit is not installed. Installing now..."
                  pip install csvkit
              fi

              sed -i '1s/act/key/g; 1s/prompt/value/g' prompts.csv
              csvjson prompts.csv > prompts.json
              echo "prompts.csv has been converted to prompts.json."
              
              if ! [ -n "$(git status --porcelain)" ]; then
                echo "No changes detected in Git repo. Skipping commit."
              else
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git commit -m "Updated!" -a
                git push
                echo "Changes pushed to Git repo."
              fi
          fi
